### ISSUE TITLE
What version of QT did you use?

### ISSUE THREAD

**Issue by danielnjoo** [vaultah/edge-detection#1]
Compiling it gives me a QtCore not found, and opening in QT gives me: 

> Error while parsing file /Users/.../edge-detection/edge-detection.pro. Giving up.

**Comment by vaultah** [comment]
I used Qt 5.7.0.

Output from the Qt Versions tab:

```
Name:  Qt 5.7.0 GCC 64bit
ABI:  x86-linux-generic-elf-64bit
Source:  /home/.../Qt/5.7/gcc_64
mkspec:  linux-g++
qmake:  /home/.../Qt/5.7/gcc_64/bin/qmake
Version:  5.7.0
```
